### ISSUE TITLE
Android: AFSocketAddress triggers DNS lookup

### ISSUE THREAD

**Issue by sweord** [kohlschutter/junixsocket#139] opened 2023-09-11 06:53 UTC
**Describe the bug**
 
Android `getByName` implementation is different from java SDK. So we cannot just add `[` prefix to the Unix socket path to prevent resolving. 

Android implementation will resolve everything and don't throw exception, so the creation will be very slow.

```
    /**
     * Determines the IP address of a host, given the host's name.
     *
     * <p> The host name can either be a machine name, such as
     * "{@code java.sun.com}", or a textual representation of its
     * IP address. If a literal IP address is supplied, only the
     * validity of the address format is checked.
     *
     * <p> For {@code host} specified in literal IPv6 address,
     * either the form defined in RFC 2732 or the literal IPv6 address
     * format defined in RFC 2373 is accepted. IPv6 scoped addresses are also
     * supported. See <a href="Inet6Address.html#scoped">here</a> for a description of IPv6
     * scoped addresses.
     *
     * <p> If the host is {@code null} then an {@code InetAddress}
     * representing an address of the loopback interface is returned.
     * See <a href="http://www.ietf.org/rfc/rfc3330.txt">RFC&nbsp;3330</a>
     * section&nbsp;2 and <a href="http://www.ietf.org/rfc/rfc2373.txt">RFC&nbsp;2373</a>
     * section&nbsp;2.5.3. </p>
     *
     * @param      host   the specified host, or {@code null}.
     * @return     an IP address for the given host name.
     * @exception  UnknownHostException  if no IP address for the
     *               {@code host} could be found, or if a scope_id was specified
     *               for a global IPv6 address.
     * @exception  SecurityException if a security manager exists
     *             and its checkConnect method doesn't allow the operation
     */
    public static InetAddress getByName(String host)
        throws UnknownHostException {
        // Android-changed: Rewritten on the top of Libcore.os.
        return impl.lookupAllHostAddr(host, NETID_UNSET)[0];
    }
```

**Comment by kohlschuetter** [comment] 2023-09-11 13:45
Thanks for reporting, @sweord !

Are you creating a lot of different addresses? What's the use case?
Why is resolution slow (even if we have to perform a DNS lookup, it shouldn't be that slow)?
What are we chasing here?

**Comment by sweord** [comment] 2023-09-12 10:45
> @sweord Can you confirm the above code change fixes your issue? I can't remember exactly why I resorted to deserialization. I'll have to check all other platforms to see if that still works now.

Thanks for your work!

I didn't know how to build android so in this project, so I tested with 2.7.0 android jni and latest self built 2.7.2-snapshot junixsocket-common.

It seems this commit cannot avoid android address resolving.  

This is the call stack: 
```
parseNumericAddressNoThrowStripOptionalBrackets:114, InetAddressUtils (libcore.net)
lookupAllHostAddr:98, Inet6AddressImpl (java.net)
getByName:1106, InetAddress (java.net)
<init>:235, InetSocketAddress (java.net)
<init>:121, AFSocketAddress (org.newsclub.net.unix)
<init>:84, AFUNIXSocketAddress (org.newsclub.net.unix)
<init>:51, AFUNIXSocketAddress (org.newsclub.net.unix)
lambda$addressConstructor$0:68, AFUNIXSocketAddress$1 (org.newsclub.net.unix)
newAFSocketAddress:-1, AFUNIXSocketAddress$1$$ExternalSyntheticLambda0 (org.newsclub.net.unix)
resolveAddress:373, AFSocketAddress (org.newsclub.net.unix)
of:173, AFUNIXSocketAddress (org.newsclub.net.unix)
of:139, AFUNIXSocketAddress (org.newsclub.net.unix)
of:126, AFUNIXSocketAddress (org.newsclub.net.unix)
start:114, SocketServer (com.tigerbro.moonphone.service)
lambda$onCreate$0$com-tigerbro-moonphone-service-SpiderSocketService:27, SpiderSocketService (com.tigerbro.moonphone.service)
run:-1, SpiderSocketService$$ExternalSyntheticLambda0 (com.tigerbro.moonphone.service)
run:1012, Thread (java.lang)
```

**Comment by kohlschuetter** [comment] 2023-09-12 11:52
@sweord Thanks for testing!
Ah right, we cannot instantiate InetSocketAddress with an InetAddress here, because hashCode/equals would only compare against the four IPv4 address bytes, and not the hostname (which in our case carries the actual address).

This could be fixed with some JNI tricks, however I really wonder whether we should go down that road.

The "proper" fix would be to not use an InetSocketAddress-derived class. On Android, this is not as critical as for other platforms, since, for example, RMI isn't available. However, it may still affect third-party code that absolutely expects InetSocketAddress-es.

junixsocket tries to somewhat (but not entirely) untangle the mess that was created in a time when "unresolved" hostnames and proper socket address were shoehorned into the same Java API (unlike, say, the POSIX C struct sockaddr API) and where IPv4/IPv6 addresses were the only meaningful address types in Java.

In hindsight, I should have just created an optional wrapper to force any SocketAddress into InetSocketAddress for the RMI use case, however that can't easily be changed for the 2.x release.

I might add a non-InetSocketAddress AFGenericSocketAddress base class, or support UnixDomainSocketAddress directly, if that works. In any case, it's not a small fix.

Is this a defect that cannot be accepted in your use case for the time being?

**Comment by sweord** [comment] 2023-09-13 00:57
I'm maintaining a wireless test software in android platform. There will be many test cases that access different addresses, so the resolving time differs a lot. 

If I'm testing with a new phone, the startup process will be very quick. But user's phone has be used for a long time, so it will start slowly and will trigger some exception. 

Android platform supports `Local Socket` API which is implemented by Unix socket. But we are using Apache-mina framework, which seems cannot work with it. I found and switched to junixsocket, and quickly added junixsocket to my project. It worked well, I didn't notice the problem. But when a new version released, many users report startup problem. I debugged the code and found the problem.

Now I switched back to localhost socket to keep the software working. If there is any improvement in junixsocket android platform, I will be very glad to test and use it.

Thank you very much!

**Comment by kohlschuetter** [comment] 2023-09-13 14:42
@sweord Thanks for providing this context. This sounds very interesting!

I think I've found a way to prevent DNS resolution on Android without further unstable JNI trickery, however trickery it still is. I'm using deserialization again, but in another context (see c077e8f).

Please verify with this change (or latest from main).

**Comment by sweord** [comment] 2023-09-14 09:48
I tested the newest code from main branch.

There might be other problem: 
Now the Unix socket can be created quickly with Apache-mina framework, and c++-jni socket client can connect to this Unix socket successfully.
But the communication was not so successful.  Jni client sent network packet, and it seems mina server cannot receive it. This was not seen in version 2.7.0.

I'm not familiar with mina framework, so I can't tell where exactly the problem is. I'll try to find it out.

**Comment by kohlschuetter** [comment] 2023-09-14 15:49
I was able to reproduce the bug locally. It's due to a regression introduced trying to fix #138.

Fixed in a7c310662393e4ce1a2c288a18a8bdbdb7140235. Please kindly try again. Thanks!

**Comment by sweord** [comment] 2023-09-15 00:51
The latest version works very well.
Thanks very much!

**Comment by kohlschuetter** [comment] 2023-09-15 10:49
Please verify with 2.7.2, just released. Thanks again for reporting, @sweord !

**Closed by kohlschuetter** 2023-09-15 10:49 UTC
Labels: enhancement

**Comment by sweord** [comment] 2023-09-25 00:49
Sorry for late test.
I have tested version 2.7.2, it worked fine on android platform.
Nice job! Thanks a lot!
