### ISSUE TITLE
AFUNIXSocketChannel selector not working with jetty

### ISSUE THREAD

**Issue by usertree** [kohlschutter/junixsocket#108] opened 2022-06-24 07:11 UTC
Are AFUNIXSocketChannel and AbstractSelector available? Can you provide an example?

**Comment by kohlschuetter** [comment] 2022-06-24 11:43
Yes, it's available. Make sure to use junixsocket 2.5.0 or newer since a few bugs have been fixed there.

Here's some code to get started:

```
    AFUNIXSelectorProvider provider = AFUNIXSelectorProvider.provider();
    AFUNIXSocketChannel sc = provider.openSocketChannel();
    sc.connect(AFUNIXSocketAddress.of(new File("/tmp/test.sock")));
    // (work with SocketChannel API)

    AFUNIXSocket socket = sc.socket(); // always succeeds
    // (work with Socket API)
    
    AFUNIXSocket sock = ...;
    sock.getChannel(); // always succeeds as well

    AbstractSelector selector = provider.openSelector();
    // work with Selector API
```

**Comment by usertree** [comment] 2022-06-24 12:17
When JunixSocket is used through the Jetty extension, AFSelector.select() appears to be invalid and the corresponding key cannot be obtained.

**Comment by kohlschuetter** [comment] 2022-06-24 12:18
Can you provide some test code that shows the bug? What's the error message / stack trace?

**Comment by usertree** [comment] 2022-06-24 12:20
package com.xinba.jetty;

import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.HttpDestination;
import org.eclipse.jetty.client.http.HttpClientTransportOverHTTP;
import org.eclipse.jetty.io.EndPoint;
import org.eclipse.jetty.io.ManagedSelector;
import org.eclipse.jetty.io.SelectorManager;
import org.newsclub.net.unix.AFUNIXSelectorProvider;
import org.newsclub.net.unix.AFUNIXSocketAddress;
import org.newsclub.net.unix.AFUNIXSocketChannel;

import java.io.IOException;
import java.net.ConnectException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.SocketException;
import java.nio.channels.SelectableChannel;
import java.nio.channels.SelectionKey;
import java.nio.channels.Selector;
import java.nio.charset.Charset;
import java.util.Map;

/**
 * uds transport by junixsocket
 *
 * @since 2022-06-06
 */
public class SOPTransportUnixSocket extends HttpClientTransportOverHTTP {

    private String socketFile;

    private static final AFUNIXSelectorProvider PROVIDER = AFUNIXSelectorProvider.getInstance();;

    /**
     * construct
     *
     * @param unixSocketPath unix socket path
     */
    public SOPTransportUnixSocket(String unixSocketPath) {
        System.out.println("SOPTransportUnixSocket 1111");
        this.socketFile = unixSocketPath;
    }

    @Override
    protected SelectorManager newSelectorManager(HttpClient client) {
        return new SOPUnixSelectorManager(client, getSelectors());
    }

    @Override
    public void connect(InetSocketAddress address, Map<String, Object> context) {
        AFUNIXSocketChannel channel = null;
        try {
            InetAddress inet = address.getAddress();
            if (!inet.isLoopbackAddress() && !inet.isLinkLocalAddress() && !inet.isSiteLocalAddress()) {
                System.out.println("unix socket cannot connect to {}" + address.getHostString());
                throw new ConnectException("unix socket cannot connect to " + address.getHostString());
            }
            AFUNIXSocketAddress afunixSocketAddress = AFUNIXSocketAddress.of(socketFile.getBytes(Charset.defaultCharset()));
            System.out.println("accept opening");
            channel = PROVIDER.openSocketChannel();
            // channel = AFUNIXSocketChannel.open();
            boolean connected = channel.connect(afunixSocketAddress);
            // channel = AFUNIXSelectorProvider.getInstance().openSocketChannel(afunixSocketAddress);
            HttpDestination destination = (HttpDestination)context.get(HTTP_DESTINATION_CONTEXT_KEY);
            HttpClient client = destination.getHttpClient();
            System.out.println("accept starting");
            configure(client, channel);
            channel.configureBlocking(false);
            getSelectorManager().accept(channel, context);
            System.out.println("accept finished");
        } catch (Throwable throwable) {
            System.out.println("connect failed, " + throwable);
            if (throwable.getClass() == SocketException.class) {
                throwable = new SocketException("Could not connect to " + address).initCause(throwable);
            }
            if (channel != null) {
                try {
                    channel.close();
                } catch (IOException ioException) {
                    System.out.println("channel close catch ioException.");
                } finally {
                    connectFailed(context, throwable);
                }
            }
        }
    }

    class SOPUnixSelectorManager extends ClientSelectorManager {

        protected SOPUnixSelectorManager(HttpClient client, int selectors) {
            super(client, selectors);
        }

        @Override
        protected Selector newSelector() throws IOException {
            return PROVIDER.openSelector();
        }

        @Override
        protected EndPoint newEndPoint(SelectableChannel channel, ManagedSelector selector, SelectionKey key) {
            SOPUnixEndPoint unixEndPoint = new SOPUnixEndPoint((AFUNIXSocketChannel) channel, selector, key, getScheduler());
            unixEndPoint.setIdleTimeout(getHttpClient().getIdleTimeout());
            return unixEndPoint;
        }
    }
}



package com.xinba.jetty;

import org.eclipse.jetty.io.ChannelEndPoint;
import org.eclipse.jetty.io.ManagedSelector;
import org.eclipse.jetty.util.thread.Scheduler;
import org.newsclub.net.unix.AFUNIXSocketChannel;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.channels.SelectionKey;

/**
 * unix endPoint
 *
 * @since 2022-06-06
 */
class SOPUnixEndPoint extends ChannelEndPoint {

    /**
     * construct
     *
     * @param channel channel
     * @param selector selector
     * @param key key
     * @param scheduler scheduler
     */
    SOPUnixEndPoint(AFUNIXSocketChannel channel, ManagedSelector selector, SelectionKey key, Scheduler scheduler) {
        super(channel, selector, key, scheduler);
    }

    @Override
    public AFUNIXSocketChannel getChannel() {
        return (AFUNIXSocketChannel) super.getChannel();
    }

    @Override
    public InetSocketAddress getLocalAddress() {
        return null;
    }

    @Override
    public InetSocketAddress getRemoteAddress() {
        return null;
    }

    @Override
    protected void doShutdownOutput() {
        try {
            getChannel().shutdownOutput();
            super.doShutdownOutput();
        } catch (IOException exception) {
            System.out.println("unix channel shutdown failed, " + exception);
        }
    }
}

**Comment by usertree** [comment] 2022-06-24 12:22
```
package com.xinba.jetty;

import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.client.HttpDestination;
import org.eclipse.jetty.client.http.HttpClientTransportOverHTTP;
import org.eclipse.jetty.io.EndPoint;
import org.eclipse.jetty.io.ManagedSelector;
import org.eclipse.jetty.io.SelectorManager;
import org.newsclub.net.unix.AFUNIXSelectorProvider;
import org.newsclub.net.unix.AFUNIXSocketAddress;
import org.newsclub.net.unix.AFUNIXSocketChannel;

import java.io.IOException;
import java.net.ConnectException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.SocketException;
import java.nio.channels.SelectableChannel;
import java.nio.channels.SelectionKey;
import java.nio.channels.Selector;
import java.nio.charset.Charset;
import java.util.Map;

/**
 * uds transport by junixsocket
 *
 * @since 2022-06-06
 */
public class SOPTransportUnixSocket extends HttpClientTransportOverHTTP {

    private String socketFile;

    private static final AFUNIXSelectorProvider PROVIDER = AFUNIXSelectorProvider.getInstance();;

    /**
     * construct
     *
     * @param unixSocketPath unix socket path
     */
    public SOPTransportUnixSocket(String unixSocketPath) {
        System.out.println("SOPTransportUnixSocket 1111");
        this.socketFile = unixSocketPath;
    }

    @Override
    protected SelectorManager newSelectorManager(HttpClient client) {
        return new SOPUnixSelectorManager(client, getSelectors());
    }

    @Override
    public void connect(InetSocketAddress address, Map<String, Object> context) {
        AFUNIXSocketChannel channel = null;
        try {
            InetAddress inet = address.getAddress();
            if (!inet.isLoopbackAddress() && !inet.isLinkLocalAddress() && !inet.isSiteLocalAddress()) {
                System.out.println("unix socket cannot connect to {}" + address.getHostString());
                throw new ConnectException("unix socket cannot connect to " + address.getHostString());
            }
            AFUNIXSocketAddress afunixSocketAddress = AFUNIXSocketAddress.of(socketFile.getBytes(Charset.defaultCharset()));
            System.out.println("accept opening");
            channel = PROVIDER.openSocketChannel();
            // channel = AFUNIXSocketChannel.open();
            boolean connected = channel.connect(afunixSocketAddress);
            // channel = AFUNIXSelectorProvider.getInstance().openSocketChannel(afunixSocketAddress);
            HttpDestination destination = (HttpDestination)context.get(HTTP_DESTINATION_CONTEXT_KEY);
            HttpClient client = destination.getHttpClient();
            System.out.println("accept starting");
            configure(client, channel);
            channel.configureBlocking(false);
            getSelectorManager().accept(channel, context);
            System.out.println("accept finished");
        } catch (Throwable throwable) {
            System.out.println("connect failed, " + throwable);
            if (throwable.getClass() == SocketException.class) {
                throwable = new SocketException("Could not connect to " + address).initCause(throwable);
            }
            if (channel != null) {
                try {
                    channel.close();
                } catch (IOException ioException) {
                    System.out.println("channel close catch ioException.");
                } finally {
                    connectFailed(context, throwable);
                }
            }
        }
    }

    class SOPUnixSelectorManager extends ClientSelectorManager {

        protected SOPUnixSelectorManager(HttpClient client, int selectors) {
            super(client, selectors);
        }

        @Override
        protected Selector newSelector() throws IOException {
            return PROVIDER.openSelector();
        }

        @Override
        protected EndPoint newEndPoint(SelectableChannel channel, ManagedSelector selector, SelectionKey key) {
            SOPUnixEndPoint unixEndPoint = new SOPUnixEndPoint((AFUNIXSocketChannel) channel, selector, key, getScheduler());
            unixEndPoint.setIdleTimeout(getHttpClient().getIdleTimeout());
            return unixEndPoint;
        }
    }
}

package com.xinba.jetty;

import org.eclipse.jetty.io.ChannelEndPoint;
import org.eclipse.jetty.io.ManagedSelector;
import org.eclipse.jetty.util.thread.Scheduler;
import org.newsclub.net.unix.AFUNIXSocketChannel;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.channels.SelectionKey;

/**
 * unix endPoint
 *
 * @since 2022-06-06
 */
class SOPUnixEndPoint extends ChannelEndPoint {

    /**
     * construct
     *
     * @param channel channel
     * @param selector selector
     * @param key key
     * @param scheduler scheduler
     */
    SOPUnixEndPoint(AFUNIXSocketChannel channel, ManagedSelector selector, SelectionKey key, Scheduler scheduler) {
        super(channel, selector, key, scheduler);
    }

    @Override
    public AFUNIXSocketChannel getChannel() {
        return (AFUNIXSocketChannel) super.getChannel();
    }

    @Override
    public InetSocketAddress getLocalAddress() {
        return null;
    }

    @Override
    public InetSocketAddress getRemoteAddress() {
        return null;
    }

    @Override
    protected void doShutdownOutput() {
        try {
            getChannel().shutdownOutput();
            super.doShutdownOutput();
        } catch (IOException exception) {
            System.out.println("unix channel shutdown failed, " + exception);
        }
    }
}


```

**Comment by usertree** [comment] 2022-06-24 12:53
Debug finds that the code is blocked and no response is returned.
![image](https://user-images.githubusercontent.com/32734356/175539951-ee4ca1dd-e06a-404a-9d8c-b45be2e14cfe.png)

**Comment by kohlschuetter** [comment] 2022-06-24 14:52
Please verify with the latest junixsocket 2.5.1-SNAPSHOT.

You may need to add the following statements to your project's Maven POM:

```
    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

**Comment by usertree** [comment] 2022-06-24 14:59
OK，I'll try. thank you very much

**Comment by kohlschuetter** [comment] 2022-06-24 21:05
Please also see the most recent addition to junixsocket (also available in the snapshots repository): junixsocket-jetty.

This artifact provides both a server connector (jetty >= 9.4.12) and a client connector (jetty >= 10.0.8). Please give it a try and let me know if that works for you.

**Comment by usertree** [comment] 2022-06-25 02:44
Due to historical reasons, we cannot upgrade JDK11 and Jetty10. Can we provide solutions based on JDK8 and Jetty9?

**Comment by usertree** [comment] 2022-06-25 08:05
During the verification, it is found that if the number of seletors exceeds 1, requests cannot be sent to the server. Is it possible that JunixSocket does not support concurrent requests?
![image](https://user-images.githubusercontent.com/32734356/175764530-76ef40a6-373f-4e34-95a6-8299ae82ffc3.png)

**Comment by kohlschuetter** [comment] 2022-06-25 16:07
A great way to find more bugs, thank you!

Please try again with the latest snapshot (>= junixsocket 2.5.1-20220625.155644) or anything with commit 6d324a6fa06785e47948659e297e75de1541d134 or later.

**Comment by joakime** [comment] 2022-06-26 01:11
> Debug finds that the code is blocked and no response is returned. ![image](https://user-images.githubusercontent.com/32734356/175539951-ee4ca1dd-e06a-404a-9d8c-b45be2e14cfe.png)

Of special note, Jetty considers a blocking select() which returns 0 to be a broken NIO implementation, and is the cause of many 100% CPU utilization side effects.
Jetty will access the selector from any number of threads, often concurrently, so that select() call should never return 0.
This is basic NIO requirements, and many custom NIO implementations get this wrong.  
The screenshot hints at the return 0 bug and some awkward locking.
If this is the case, you have a way to go before this will work reliably on Jetty.

**Comment by kohlschuetter** [comment] 2022-06-26 13:18
@joakime Did you try with the latest build I mentioned? Can you reproduce your issue?

I threw a bunch of parallel requests at it, and it seems to work for me, also with multiple selectors. Are you seeing a concrete issue with junixsocket's handling of `Selector#select`, or is this a hypothetical concern?

Regarding `select()` not allowed to return 0: According to the [Java API documentation](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/Selector.html#select--), it is perfectly OK to return 0:

> "The number of keys, possibly zero, whose ready-operation sets were updated",

So I think that is not the NIO requirement you mention. Is there additional documentation around this point? 

By the way, there was an indeed a bug in the client connector side of things (missing Selector implementation override). I've now added (a slightly modified) `org.eclipse.jetty.unixdomain.server.UnixDomainTest` to junixsocket-jetty's test suite, and all these jetty tests seem to pass now.

I wonder what else is missing?

Please test with the latest snapshot (20220626.130729-5 or newer), or commit d366394ac7ae22683eb46e1ac113136f80507e1d or newer from git.

**Comment by gregw** [comment] 2022-06-26 22:40
@joakime I'm not so worried by that locking... if/when we do call select() from multiple threads, we expect the implementation to internally mutually exclude and one to eventually to respond and the next to then take over and block waiting for further events.   So that locking is fine.   Also, I think with our latest code, where the selector is always called from our producer, we should no longer do concurrent calls to select anyway.  But each select is highly likely to be done by a different thread as we prefer to allow any thread woken up in a select call to proceed to handle those selections rather than hand off to another thread (likely on different CPU with cold cache etc.).

However, we definitely do expect a blocking call to select to not immediately return with 0, else we end up in a busy loop.  Previously we made efforts to detect such loops as it was decided it was better to die and allow a restart rather than to continue to hammer on a non functional busy loop selector.    But our currect code no longer detects such a case, rather it only has the option to try a selectNow instead before looping.     So if select() does return 0 without pause, you will be in a busy loop.

**Comment by kohlschuetter** [comment] 2022-06-28 15:07
@gregw `AFSelector#select` should not return immediately (unless an exception is thrown, e.g., when the socket is closed).

@usertree Now it would be a great time to verify that everything works for you with the latest code. Since it includes some bug fixes, I'd like to release 2.5.1 soon. If I don't hear from you until Thursday (June 30), I will assume everything works now (but I might be slightly sad that you didn't reply). Cheers!

**Comment by usertree** [comment] 2022-06-29 07:43
Which version can I use, currently using 2.5.1 - SNAPSHOT still has seletor concurrency issues.

**Comment by kohlschuetter** [comment] 2022-06-29 10:48
@usertree
When using snapshot dependencies, there is a chance that you're not on the most recent one.

Please verify that you test with 2.5.1-20220628.145818-6.

```
<dependency>
    <groupId>com.kohlschutter.junixsocket</groupId>
    <artifactId>junixsocket-common</artifactId>
    <version>2.5.1-20220628.145818-6</version>
</dependency>
<dependency>
    <groupId>com.kohlschutter.junixsocket</groupId>
    <artifactId>junixsocket-jetty</artifactId>
    <version>2.5.1-20220628.145818-6</version>
</dependency>
<repositories>
  <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
          <enabled>false</enabled>
      </releases>
      <snapshots>
          <enabled>true</enabled>
      </snapshots>
  </repository>
</repositories>
```

**Comment by usertree** [comment] 2022-06-30 01:58
Sorry I can't rely on 2.5.1-20220628.145818-6 from https://oss.sonatype.org/content/repositories/snapshots/. In addition, the list of snapshots cannot be viewed.

**Comment by kohlschuetter** [comment] 2022-06-30 10:38
I'm not sure I understand what "can't rely" means in this context. I assume you're having problems accessing that snapshot?
You can browse the artifacts here: https://oss.sonatype.org/content/repositories/snapshots/com/kohlschutter/junixsocket/

If you run your tests on your own machine, try deleting your m2 repository cache for junixsocket, e.g.,, delete the contents in `~/.m2/repository/com/kohlschutter/junixsocket`

If you're still having issues to get the right snapshot, I'd recommend trying to build junixsocket from source.

I'm pretty confident that we've captured the `select()` bugs. To rule out bugs in your implementation vs junixsocket's jetty code, try using AFSocketServerConnector from junixsocket-jetty. Instructions are here: https://github.com/kohlschutter/junixsocket/blob/master/junixsocket-jetty/README.md

**Comment by kohlschuetter** [comment] 2022-07-17 16:29
Closing resolved ticket due to inactivity. Please re-open if you find any problems. Thanks for reporting!

**Comment by kohlschuetter** [comment] 2023-07-12 15:27
@kevink-sq Thanks for the update! This looks like a different bug. Can you please file a new issue with some code to replicate this? Cheers!

**Closed** 2023-07-12 15:26 UTC
Labels: bug, verify

**Comment by kohlschuetter** [comment] 2023-07-12 16:25
@kevink-sq Following up with https://github.com/kohlschutter/junixsocket/issues/135
